import type { NextPage } from 'next'
import Head from 'next/head'
import React, { useState } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import { DocumentTableRow } from '../components/DocumentTableRow';
import { Table, Container, Button, InputGroup, FormControl } from 'react-bootstrap';

const Home: NextPage = () => {
  const [newDocName, setNewDocName] = useState('');
  const [docList, setDocList] = useState([
    {
      name: 'Doc 1',
    },
    {
      name: 'Doc 2',
    },
    {
      name: 'Doc 3',
    },
  ]);

  const removeDocFromList = (name: string): void => {
    setDocList(docList.filter((d) => d.name !== name));
  }

  const addDoc = () => {
    if (newDocName.length > 0) {
      if (docList.filter((d) => d.name === newDocName).length === 0) {
        setDocList([...docList, {name: newDocName}]);
        setNewDocName('');
      }
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>

        <h1>My Documents</h1>
        <InputGroup className="mb-3">
          <FormControl
            placeholder="Document Name"
            aria-label="Document Name"
            value={newDocName}
            onChange={(e) => setNewDocName(e.target.value)}
            type="text"
          />
          <Button data-testid={'add-document'} variant="outline-secondary" onClick={addDoc}>
          Add Document
          </Button>
        </InputGroup>
        <Table striped bordered hover>
          <thead>
            <tr>
              <th>Document Name</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {docList.map(({ name }) => {
              return (
                <DocumentTableRow key={name} name={name} removeDocFromList={removeDocFromList} />
              )
            })}
          </tbody>
        </Table>
        </Container>
      </main>
    </div>
  );
}

export default Home
